"""add_student_demographics_fields

Revision ID: 9b37bd053b27
Revises: 
Create Date: 2026-08-27 12:55:37.442127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b37bd053b27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('alternative_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('students', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('students', sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('students', sa.Column('residence', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('students', sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'county')
    op.drop_column('students', 'residence')
    op.drop_column('students', 'nationality')
    op.drop_column('students', 'email')
    op.drop_column('students', 'alternative_phone')
    # ### end Alembic commands ###
