"""create_competitions_table

Revision ID: fbb05bc723b2
Revises: 9b37bd053b27
Create Date: 2026-08-27 15:02:15.086294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbb05bc723b2'
down_revision: Union[str, None] = '9b37bd053b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edition_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('host_org', sa.Enum('JAMIA_MOSQUE', 'RELIGIOUS_ATTACHE', 'JOINT_COLLABORATION', 'CUSTOM', name='hostorganization'), nullable=False),
    sa.Column('host_org_name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host_org_name_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONCLUDED', 'DRAFT', name='competitionstatus'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('grand_finale_date', sa.Date(), nullable=True),
    sa.Column('venue_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('venue_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('theme_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_ar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=False),
    sa.Column('winners', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_is_current'), 'competitions', ['is_current'], unique=False)
    op.create_index(op.f('ix_competitions_status'), 'competitions', ['status'], unique=False)
    op.create_index(op.f('ix_competitions_title_en'), 'competitions', ['title_en'], unique=False)
    op.create_index(op.f('ix_competitions_year'), 'competitions', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitions_year'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_title_en'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_status'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_is_current'), table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
